import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import matplotlib.colorbar as mcolorbar
import matplotlib.colors as mcolors

# ── Y-axis (stability diagram) ────────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(0.9, 4))
fig.patch.set_alpha(0); ax.patch.set_alpha(0)
ax.set_ylim(820, 845)
ax.yaxis.set_major_locator(ticker.MultipleLocator(10))
ax.yaxis.set_minor_locator(ticker.MultipleLocator(5))
ax.tick_params(axis='y', which='major', labelsize=16, length=6, width=1.2, direction='out')
ax.tick_params(axis='y', which='minor', length=3, width=1.0, direction='out', labelleft=False)
ax.xaxis.set_visible(False)
ax.spines['top'].set_visible(False); ax.spines['bottom'].set_visible(False)
ax.spines['right'].set_visible(False); ax.spines['left'].set_linewidth(2.5)
ax.set_ylabel('CS(inner) (mV)', fontsize=14, labelpad=6)
fig.tight_layout(pad=0.3)
fig.savefig('yaxis.png', transparent=True, bbox_inches='tight')
plt.close(fig)

# ── X-axis (stability diagram) ────────────────────────────────────────────────
fig2, ax2 = plt.subplots(figsize=(4, 0.9))
fig2.patch.set_alpha(0); ax2.patch.set_alpha(0)
ax2.set_xlim(0.6, 1.3)
ax2.xaxis.set_major_locator(ticker.MultipleLocator(0.2))
ax2.xaxis.set_minor_locator(ticker.MultipleLocator(0.1))
ax2.tick_params(axis='x', which='major', labelsize=16, length=6, width=1.2, direction='out')
ax2.tick_params(axis='x', which='minor', length=3, width=1.0, direction='out', labelbottom=False)
ax2.yaxis.set_visible(False)
ax2.spines['top'].set_visible(False); ax2.spines['left'].set_visible(False)
ax2.spines['right'].set_visible(False); ax2.spines['bottom'].set_linewidth(2.5)
ax2.set_xlabel('5g(outer) (V)', fontsize=14, labelpad=6)
fig2.tight_layout(pad=0.3)
fig2.savefig('xaxis.png', transparent=True, bbox_inches='tight')
plt.close(fig2)

# ── Colorbar ──────────────────────────────────────────────────────────────────
fig3, ax3 = plt.subplots(figsize=(0.9, 4))
fig3.patch.set_alpha(0); ax3.patch.set_alpha(0)
norm = mcolors.Normalize(vmin=0, vmax=25)
cb = mcolorbar.ColorbarBase(ax3, cmap='inferno', norm=norm, orientation='vertical')
cb.set_ticks([0, 5, 10, 15, 20, 25])
cb.ax.tick_params(labelsize=16, length=6, width=1.2, direction='out')
cb.set_label('G (µS)', fontsize=14, labelpad=8)
fig3.tight_layout(pad=0.3)
fig3.savefig('colorbar.png', transparent=True, bbox_inches='tight')
plt.close(fig3)

# ── Y-axis (current vs freq) ──────────────────────────────────────────────────
fig4, ax4 = plt.subplots(figsize=(0.9, 4))
fig4.patch.set_alpha(0); ax4.patch.set_alpha(0)
ax4.set_ylim(0, 25)
ax4.yaxis.set_major_locator(ticker.MultipleLocator(10))
ax4.yaxis.set_minor_locator(ticker.MultipleLocator(5))
ax4.tick_params(axis='y', which='major', labelsize=16, length=6, width=1.25, direction='out')
ax4.tick_params(axis='y', which='minor', length=3, width=1.0, direction='out', labelleft=False)
ax4.xaxis.set_visible(False)
ax4.spines['top'].set_visible(False); ax4.spines['bottom'].set_visible(False)
ax4.spines['right'].set_visible(False); ax4.spines['left'].set_linewidth(1.25)
ax4.set_ylabel('current (pA)', fontsize=14, labelpad=6)
fig4.tight_layout(pad=0.3)
fig4.savefig('yaxis_current.png', transparent=True, bbox_inches='tight')
plt.close(fig4)

# ── X-axis (current vs freq) ──────────────────────────────────────────────────
fig5, ax5 = plt.subplots(figsize=(4, 0.9))
fig5.patch.set_alpha(0); ax5.patch.set_alpha(0)
ax5.set_xlim(121.65, 122.15)
ax5.xaxis.set_major_locator(ticker.FixedLocator([121.8, 122.0]))
ax5.xaxis.set_minor_locator(ticker.MultipleLocator(0.1))
ax5.tick_params(axis='x', which='major', labelsize=11, length=6, width=1.2, direction='out')
ax5.tick_params(axis='x', which='minor', length=3, width=1.0, direction='out', labelbottom=False)
ax5.yaxis.set_visible(False)
ax5.spines['top'].set_visible(False); ax5.spines['left'].set_visible(False)
ax5.spines['right'].set_visible(False); ax5.spines['bottom'].set_linewidth(1.25)
ax5.set_xlabel('freq (MHz)', fontsize=14, labelpad=6)
fig5.tight_layout(pad=0.3)
fig5.savefig('xaxis_freq.png', transparent=True, bbox_inches='tight')
plt.show()
plt.close(fig5)

# ── Y-axis (temperature dependence) ──────────────────────────────────────────
fig6, ax6 = plt.subplots(figsize=(0.9, 4))
fig6.patch.set_alpha(0); ax6.patch.set_alpha(0)
ax6.set_ylim(-0.05, 1.7)
ax6.yaxis.set_major_locator(ticker.MultipleLocator(0.4))
ax6.yaxis.set_minor_locator(ticker.MultipleLocator(0.2))
ax6.tick_params(axis='y', which='major', labelsize=16, length=6, width=1.25, direction='out')
ax6.tick_params(axis='y', which='minor', length=3, width=1.0, direction='out', labelleft=False)
ax6.xaxis.set_visible(False)
ax6.spines['top'].set_visible(False); ax6.spines['bottom'].set_visible(False)
ax6.spines['right'].set_visible(False); ax6.spines['left'].set_linewidth(1.25)
fig6.tight_layout(pad=0.3)
fig6.savefig('yaxis_temp.png', transparent=True, bbox_inches='tight')

# ── X-axis (temperature dependence) ──────────────────────────────────────────
fig7, ax7 = plt.subplots(figsize=(4, 0.9))
fig7.patch.set_alpha(0); ax7.patch.set_alpha(0)
ax7.set_xlim(-5, 165)
ax7.xaxis.set_major_locator(ticker.MultipleLocator(40))
ax7.xaxis.set_minor_locator(ticker.MultipleLocator(20))
ax7.tick_params(axis='x', which='major', labelsize=11, length=6, width=1.25, direction='out')
ax7.tick_params(axis='x', which='minor', length=3, width=1.0, direction='out', labelbottom=False)
ax7.yaxis.set_visible(False)
ax7.spines['top'].set_visible(False); ax7.spines['left'].set_visible(False)
ax7.spines['right'].set_visible(False); ax7.spines['bottom'].set_linewidth(1.25)
fig7.tight_layout(pad=0.3)
fig7.savefig('xaxis_temp.png', transparent=True, bbox_inches='tight')

plt.show()

# ── Y-axis (power spectral density) ──────────────────────────────────────────
fig8, ax8 = plt.subplots(figsize=(0.5, 4))
fig8.patch.set_alpha(0); ax8.patch.set_alpha(0)
ax8.set_ylim(0, 21)
ax8.yaxis.set_major_locator(ticker.MultipleLocator(5))
ax8.yaxis.set_minor_locator(ticker.MultipleLocator(2.5))
ax8.tick_params(axis='y', which='major', labelsize=0, length=6, width=1.25, direction='out')
ax8.tick_params(axis='y', which='minor', length=3, width=1.0, direction='out', labelleft=False)
ax8.xaxis.set_visible(False)
ax8.spines['top'].set_visible(False); ax8.spines['bottom'].set_visible(False)
ax8.spines['right'].set_visible(False); ax8.spines['left'].set_linewidth(1.25)
fig8.tight_layout(pad=0.3)
fig8.savefig('yaxis_psd.png', transparent=True, bbox_inches='tight')

# ── X-axis (power spectral density) ──────────────────────────────────────────
fig9, ax9 = plt.subplots(figsize=(4, 0.5))
fig9.patch.set_alpha(0); ax9.patch.set_alpha(0)
ax9.set_xlim(121.907, 121.913)
ax9.xaxis.set_major_locator(ticker.MultipleLocator(0.002))
ax9.xaxis.set_minor_locator(ticker.MultipleLocator(0.001))
ax9.tick_params(axis='x', which='major', labelsize=0, length=6, width=1.25, direction='out')
ax9.tick_params(axis='x', which='minor', length=3, width=1.0, direction='out', labelbottom=False)
ax9.yaxis.set_visible(False)
ax9.spines['top'].set_visible(False); ax9.spines['left'].set_visible(False)
ax9.spines['right'].set_visible(False); ax9.spines['bottom'].set_linewidth(1.25)
fig9.tight_layout(pad=0.3)
fig9.savefig('xaxis_psd.png', transparent=True, bbox_inches='tight')

plt.show()